# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-13 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='description',
            field=models.CharField(default='description', max_length=255),
            preserve_default=False,
        ),
    ]
