# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-13 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allshows', '0002_tvshow_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='description',
            new_name='desc',
        ),
    ]
