# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-13 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allshows', '0003_auto_20181113_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='releasedate',
            new_name='date',
        ),
    ]
